### ISSUE TITLE
Getting deprecated warning for using "desired_capabilities"

### ISSUE THREAD

**Issue by zeeshanyshaikh** [LambdaTest/Robot-Selenium-Sample#10]
Am getting error as below

`[ WARN ] desired_capabilities has been deprecated and removed. Please use options to configure browsers as per documentation.`

Please update the code on how to use the LT options in `options` argument of `Open Browser` keyword.

**Comment by 4DvAnCeBoY** [comment]
Thanks for sharing @zeeshanyshaikh , The repo had dependency on Selenium2Library, now this has been upgraded to new robot selenium library. Now the issue has been fixed

Please checkout master branch.
